### ISSUE TITLE
Still being worked on?

### ISSUE THREAD

**Issue by MichaelHillcox** [hilburn/AdvancedSystemsManager#93]
Hi, 

Been following this for quite a while. I have been really looking forward to a stable release. Hows the development going. not seen much activity for quite some time.

Thanks, 
Michael.

**Comment by way2muchnoise** [comment]
@hilburn hasn't really been around. So I don't think it is being worked on.

**Comment by MichaelHillcox** [comment]
@way2muchnoise Well thats a bugger. I was hoping this would be finished. Maybe i will have to finish off learning java and help out with the development. Weren't you helping out with this for a while?

**Comment by way2muchnoise** [comment]
I was helping left and right but hiburn did most of the work as it was his plan. As he has been MIA for a while now and I didn't work on it by myself.

**Comment by MichaelHillcox** [comment]
@way2muchnoise Real shame. Hope he comes back.

**Comment by bpwhelan** [comment]
He did reply to a comment on his last commit on November 11th saying he had most of the bugs fixed in dev but could just never push it. It would be nice to have some of the big bugs fixed, but it is what it is, have to find a new way to do things (rather than switching back to SFM). However, Reddit is probably one of the best ways to reach him.

**Comment by MichaelHillcox** [comment]
Bump @hilburn You still working on this or is it officially dead?

**Comment by Tcll** [comment]
bump again @hilburn
working on a 1.7.10 modpack (some vital mods aren't available in newer versions), and I still get the same reported issues...

my pack actually requires this mod to replace other needless mods that use more RAM and don't perform as well.
